[mongodb]
uri = "mongodb+srv://Yash:yash123@cluster0.nuhyy6j.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"

[encryption]
key = "8Q95Hu1PNONZx0-cJ6K3JRIbd9yvZjoaMEnjTd3RrVs="

[gemini]
api_key = "AIzaSyBtf-4EdaDv-h9YNqJAkW3uQXFocTVhAS0"



